### ISSUE TITLE
TypeError - handler is not a function

### ISSUE THREAD

**Issue by RealityCtrl** [DataDog/datadog-lambda-js#237]
## Expected Behavior
Lambda layer functions correctly

## Actual Behavior
As of 5am BST the datadog lambda layer versions 62 and 64 for node 14.x in us-east-1 are intermittently exhibiting a type error on lambda execution.  Same layer in eu-west-1 with same code is not exhibiting the issue.  The lambda functioned correctly for 18 hours with version 62 of the layer then started getting the type error which persisted for 90 minutes until same code was redeployed with version 64 of the layer.  This then worked for 2 hours before giving the same type error and has done so for the last hour. 

## Steps to Reproduce the Problem

  1. Apply the layer on a lambda in us-east-1

## Specifications

  - Datadog Lambda Layer version: 62 & 64
  - Node version: 14.x

## Stacktrace

```
{
    "errorType": "TypeError",
    "errorMessage": "handler is not a function",
    "stack": [
        "TypeError: handler is not a function",
        "    at /opt/nodejs/node_modules/datadog-lambda-js/utils/handler.js:148:25",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/datadog-lambda-js/index.js:168:62)",
        "    at step (/opt/nodejs/node_modules/datadog-lambda-js/index.js:44:23)",
        "    at Object.next (/opt/nodejs/node_modules/datadog-lambda-js/index.js:25:53)",
        "    at /opt/nodejs/node_modules/datadog-lambda-js/index.js:19:71",
        "    at new Promise (<anonymous>)",
        "    at __awaiter (/opt/nodejs/node_modules/datadog-lambda-js/index.js:15:12)",
        "    at /opt/nodejs/node_modules/datadog-lambda-js/index.js:162:108",
        "    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:97:56",
        "    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:48:56"
    ]
}
```

**Comment by lielran** [comment]
@aterreno I've tried to add the layer again and the verify btn works. so I guess the layer do exist

**Comment by aterreno** [comment]
Ok I'll do the same.

**Comment by aterreno** [comment]
Amazing @lielran  that really seems to work - I think it's the only thing I haven't tried, I was going to just rip off datadog complitely

**Comment by gpoitch** [comment]
Same issue has been happening for us with a simple lambda for the last 12 hours - no datadog or layers.
Stumbled upon this searching the internet for similar cases.

**Comment by Czechh** [comment]
@matvi3nko AWS team

**Comment by ProficientBell** [comment]
Any updates on what happened here?  Wondering if it's worth hosting this layer in my aws account or just doing away with it entirely and moving to another tracing platform

**Comment by tianchu** [comment]
Sorry for the late response, we noticed that certain Node14.x Lambda functions deployed in us-east-1 were observing intermittent errors (“handler is not a function”) between 7:20PM October 13th EDT and 8:00AM October 14th EDT. We are actively investigating the root cause with the AWS Lambda team, and will share the results with the community as soon as possible. Please subscribe this issue or contact Datadog support (support@datadoghq.com) for the investigation results and additional technical details.

**Comment by alexis-caylent** [comment]
If it helps, my team has experienced the very same issue in ca-central-1 as well

**Comment by alexis-caylent** [comment]
> 
> 
> @alexis-caylent any chance you are using container image from ECR?

Nope, we are not using container images

**Comment by aterreno** [comment]
Oh I see so you mean wrap but keep the layer, makes sense

**Comment by phil-gratifypay** [comment]
I still have this problem after I upgraded docker to 4.1.1.
The lambda function is in a NodeJS environment. The image is **nodejs14.x-x86_64-9a2e4373acc332cd69e90c7f3**. 
This image might caused the problem because the function can successfully run in an earlier version. But, how can I specify a particular image for the lambda function if I want to use an earlier version of NodeJS environment?

**Comment by tianchu** [comment]
@phil-gratifypay you can see the usage tab of https://gallery.ecr.aws/lambda/nodejs, and the latest version public.ecr.aws/lambda/nodejs:14 should work. Alternatively, you can upgrade your datadog-lambda-js to the latest version https://github.com/DataDog/datadog-lambda-js/releases/tag/v4.65.0, which should help stop the error as well.

**Comment by phil-gratifypay** [comment]
@tianchu Thanks for your help. After I have changed the value of nodeLayerVersion to 65 and extensionLayerVersion to 13  in constructor of Datadog, the problem is gone.
`new Datadog(this, "Datadog", {
nodeLayerVersion: 65, extensionLayerVersion: 13, ... })`

**Comment by tedyu** [comment]
@tianchu 
What's the recommended version of datadog-lambda-js release for node.js 16 and 18 releases, respectively ?

Thanks
